name: LoyHelper
main: io.loyloy.loyhelper.spigot.LoyHelper
version: 1.0
author: Melonking
description: Loy compatability and features.

commands:
  reloadhelper:
    description: Reloads the loy helper!